version: "3.8"
services:

  db:
    image: postgres:12-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME?Variable not set}.app-db-data == true

  backend:
    image: '${DOCKER_REGISTRY}/giskard-backend:${TAG-latest}'
    volumes:
      - app-files-bucket:/app/files-bucket
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: '${INSTALL_DEV-false}'

  frontend:
    image: '${DOCKER_REGISTRY}/giskard-frontend:${TAG-latest}'
    depends_on:
      - backend
    env_file:
      - .env
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

  jupyter:
    build:
      context: ./backend/demo-notebook
      dockerfile: demo-notebook.dockerfile
    entrypoint:
      - /usr/local/bin/start.sh
      - jupyter
      - notebook
      - --NotebookApp.token=''
    volumes:
      - ./backend/demo-notebook/notebook:/home/jovyan
    ports:
      - '18888:8888'

volumes:
  app-db-data:
  app-files-bucket:
